# fly.toml app configuration file generated for realzero-back on 2024-06-26T16:11:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "realzero-back"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true  # 필요에 따라 true 또는 false로 설정
  auto_start_machines = true
  min_machines_running = 1  # 최소 실행 머신 수를 1로 설정하여 자동 중지 방지
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.tcp_checks]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"
